import type { Metadata } from "next";

import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet" /> {/* 引入 Poppins 字体 */}
      </head>
      <body
        className="antialiased"
      >
        {children}
      </body>
    </html>
  );
}
